### ISSUE TITLE
✨ add `gdtf-types` to docs

### ISSUE THREAD

**Issue by lukas-runge** [oshifty/vision#14]
As the types are referenced within the classes of this repo similarly to `UDR` types it would be awesome to be able to include them in the `docs`. 🔥

see https://www.npmjs.com/package/gdtf-types
ty @hrueger for generating those 🙌

🚧  Currently document generator fails to parse / include the library. This needs further investigation. 🚧

**Comment by hrueger** [comment]
Can you share more info? What do you mean by *fails to parse / include the library*. For me, it does not throw an error. Do you get an error message or is it just as if that packages was not there?

**Comment by lukas-runge** [comment]
> Sadly it seems like it's not valid typescript? In my dev environment the linter complains

> Interesting. Does not happen for me. Can you share the error @lukas-runge?

I just checked the errors again. It's all linter errors from `eslint` that only occur, when the file is copied to the `src` directory.

- `Unexpected var, use let or const instead.`
- `An interface declaring no members is equivalent to its supertype.`

So it seems to indeed be valid javascript at least.

---
> and document generator fails to parse / include the library

> do you see an error here? I don't.

I also don't get errors in the console. It just does not compile into the result. It's just an empty page like so 🤷‍♂️

![GDTF _ Home](https://github.com/oshifty/vision/assets/21328241/3a0b15dc-a021-41ef-b5b1-145fe762bb3a)


_Originally posted by @hrueger in https://github.com/oshifty/vision/issues/9#issuecomment-1695165426_

**Comment by hrueger** [comment]
How do you copy the file? Is there a command for that in the `package.json` or how is the workflow here? Just trying to reproduce that

**Comment by hrueger** [comment]
By the way, there is no js at all. It's just two `.d.ts` files.

**Comment by lukas-runge** [comment]
> How do you copy the file? Is there a command for that in the `package.json` or how is the workflow here? Just trying to reproduce that

I was just trying to figure out a way to "feed" typedoc ("forcefully" 🙃) with the type definitions for `gdtf`. This is why I copied them over into the `src` dir. But it didn't help me in any way. 😆

> By the way, there is no js at all. It's just two `.d.ts` files.

Yes - you are absolutely right. What I said does not make any sense. There is a distinct difference between a transpiler and a linter that I haven't caught on, when writing earlier issues on the topic. 🫣
